import './globals.css';
import './capabilities-overrides.css';
import './industry-overrides.css';
import './about-overrides.css';
import './ecosystem-overrides.css';
import './methodology-overrides.css';
import './intralogistica/polish.css';
import './intralogistica/cainiao-fix.css';
import './intralogistica/alignment-fix.css';
import './gestion-orquestacion/pill-fix.css';
import './gestion-orquestacion/dashboard-real-fix.css';
import './gestion-orquestacion/logo-fix.css';
import './gestion-orquestacion/partners-section-fix.css';
import './gestion-orquestacion/partner-section-exact.css';
import './gestion-orquestacion/partner-section-final-fix.css';
import './gestion-orquestacion/final-cta-fix.css';
import './gestion-orquestacion/final-visual-fix.css';
import './gestion-orquestacion/partner-section-clean.css';
import './gestion-orquestacion/final-cta-clean.css';
import './gestion-orquestacion/cta-copy-fix.css';
import './gestion-orquestacion/section9-final-lock.css';
import './gestion-orquestacion/florim-logo-fix.css';
import './gestion-orquestacion/florim-logo-final.css';
import './subpages-sticky-header.css';
import './home-logo-fix.css';
import CapabilityLinks from './CapabilityLinks';
export const metadata={title:'Innov | Supply Chain Solutions',description:'Soluciones integrales de WMS, automatización e integración tecnológica.'};
export default function RootLayout({children}){return <html lang="es"><body><style dangerouslySetInnerHTML={{__html:`body:has(#inicio) > main > header{position:fixed!important;top:0!important;left:0!important;width:100%!important;z-index:9999!important}body:has(#inicio) > main > section[id]{scroll-margin-top:102px!important}`}} />{children}<CapabilityLinks/></body></html>}