'use client';
import {useEffect,useState} from 'react';
const slides=['https://images.unsplash.com/photo-1586528116493-da8c8f8b9a3f?auto=format&fit=crop&w=1800&q=85','https://images.unsplash.com/photo-1565610222536-ef125c59da2e?auto=format&fit=crop&w=1800&q=85','https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=1800&q=85'];
const industries=[['01','Retail & E-commerce','https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=900&q=80'],['02','Logística, Distribución & 3PL','https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=900&q=80'],['03','Manufactura & Automotriz','https://images.unsplash.com/photo-1565043666747-69f6646db940?auto=format&fit=crop&w=900&q=80']];
const steps=['Entendemos objetivos y retos','Diagnosticamos la operación','Diseñamos alternativas','Validamos el caso financiero','Implementamos e integramos','Medimos y evolucionamos'];
export default function Home(){const [i,setI]=useState(0);const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);useEffect(()=>{const t=setInterval(()=>setI(x=>(x+1)%slides.length),5000);return()=>clearInterval(t)},[]);async function submit(e){e.preventDefault();setBusy(true);const data=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});setBusy(false);if(r.ok){setSent(true);e.currentTarget.reset()}}return <main>
<header><a className="logo" href="#inicio">INNOV<span>SUPPLY CHAIN SOLUTIONS</span></a><nav>{[['Retos Logísticos','#retos'],['Capacidades','#capacidades'],['Cómo Trabajamos','#metodologia'],['Experiencia y Resultados','#industria'],['Nosotros','#nosotros'],['Contacto','#contacto']].map(x=><a key={x[0]} href={x[1]}>{x[0]}</a>)}</nav><a className="navCta" href="#contacto">HABLEMOS</a></header>
<section id="inicio" className="hero"><div className="heroBg" style={{backgroundImage:`linear-gradient(90deg,rgba(35,10,61,.96),rgba(35,10,61,.52),rgba(35,10,61,.15)),url(${slides[i]})`}}/><div className="heroText"><p className="eyebrow">SUPPLY CHAIN SOLUTIONS</p><h1>Transformamos la operación de tu almacén en ventaja competitiva.</h1><p>Soluciones integrales de WMS, automatización e integración tecnológica para lograr operaciones más eficientes, visibles y rentables.</p><div className="actions"><a href="#capacidades" className="primary">CONOCE NUESTRAS SOLUCIONES</a><a href="#contacto" className="secondary">HABLEMOS DE TU PROYECTO</a></div></div><div className="dots">{slides.map((_,n)=><button aria-label={`Imagen ${n+1}`} className={n===i?'active':''} onClick={()=>setI(n)} key={n}/>)}</div></section>
<section id="retos" className="intro"><p className="eyebrow purple">LOS RETOS</p><h2>Los grandes retos que frenan el desempeño de una operación logística.</h2><p>Antes de implementar tecnología, identificamos las restricciones que realmente afectan tu operación y construimos soluciones orientadas a resultados medibles.</p><div className="cards"><article><b>01</b><h3>Productividad y costo</h3><p>Reducimos movimientos innecesarios, tiempos improductivos y costos operativos.</p></article><article><b>02</b><h3>Capacidad y crecimiento</h3><p>Diseñamos operaciones preparadas para crecer sin perder control ni eficiencia.</p></article><article><b>03</b><h3>Inventario y servicio</h3><p>Mayor visibilidad, exactitud de inventario y cumplimiento de niveles de servicio.</p></article></div></section>
<section id="capacidades" className="dark"><div className="split"><div><p className="eyebrow">CAPACIDADES</p><h2>Tecnología aplicada a los retos reales de tu operación.</h2></div><p>Integramos WMS, automatización, datos y tecnología para convertir información operativa en decisiones y resultados.</p></div><div className="capGrid"><span>WMS & Control de Almacén</span><span>Automatización</span><span>Integración de Sistemas</span><span>Analítica & Visibilidad</span><span>Optimización Operativa</span><span>Transformación Digital</span></div></section>
<section id="metodologia" className="method"><p className="eyebrow purple">CÓMO TRABAJAMOS</p><h2>Una metodología enfocada en resultados.</h2><div className="steps">{steps.map((s,n)=><article key={s}><b>{String(n+1).padStart(2,'0')}</b><h3>{s}</h3></article>)}</div><a className="textLink" href="#contacto">Conocer nuestra metodología completa →</a></section>
<section id="industria" className="industry"><p className="eyebrow purple">EXPERIENCIA Y RESULTADOS</p><h2>Indicadores que reflejan el impacto de la transformación logística en cada industria.</h2><p>Cada sector enfrenta restricciones diferentes. Nuestra experiencia nos permite enfocar la transformación en los indicadores operativos y económicos que tienen mayor relevancia para cada tipo de operación.</p><div className="industryGrid">{industries.map(x=><article key={x[0]}><img src={x[2]}/><div><b>{x[0]}</b><h3>{x[1]}</h3></div></article>)}</div></section>
<section id="nosotros" className="about"><p className="eyebrow">NOSOTROS</p><h2>Experiencia logística respaldada por tecnología.</h2><p>Somos un equipo especializado en diseñar, integrar e implementar soluciones que conectan personas, procesos y tecnología.</p></section>
<section id="contacto" className="contact"><div><p className="eyebrow purple">CONTACTO</p><h2>Hablemos de tu proyecto.</h2><p>Cuéntanos el reto de tu operación y construyamos una solución.</p></div><form onSubmit={submit}><input name="name" placeholder="Nombre" required/><input name="company" placeholder="Empresa"/><input name="email" type="email" placeholder="Correo electrónico" required/><input name="phone" placeholder="Teléfono"/><textarea name="message" placeholder="Cuéntanos sobre tu proyecto" rows="5" required/><input name="website" className="hp" tabIndex="-1" autoComplete="off"/><button disabled={busy}>{busy?'ENVIANDO...':'ENVIAR PROYECTO →'}</button>{sent&&<small>Mensaje enviado correctamente.</small>}</form></section>
<footer><div className="logo">INNOV<span>SUPPLY CHAIN SOLUTIONS</span></div><p>© 2026 Innov. Todos los derechos reservados.</p></footer></main>}